sudo: false
language: python
python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"


cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install --upgrade pip wheel setuptools
  - pip install tox-travis coveralls

branches:
  - master

script: tox

after_success:
  - coveralls

before_install:
  - sudo apt-get install -y xmlsec1 libffi6

matrix:
  include:
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=isort
